[package]
name = "zluda_redirect"
version = "0.0.0"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[target.'cfg(windows)'.dependencies]
detours-sys = { path = "../detours-sys" }
zluda_windows = { path = "../zluda_windows" }
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_System_JobObjects",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
] }
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_System_JobObjects",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
] }
unwrap_or = "1.0.1"
widestring = "1.2.1"

[package.metadata.zluda]
windows_only = true
