[package]
name = "zluda_redirect"
version = "0.0.0"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[target.'cfg(windows)'.dependencies]
detours-sys = { path = "../detours-sys" }
zluda_windows = { path = "../zluda_windows" }

[package.metadata.zluda]
windows_only = true
