[package]
name = "dark_api"
version = "0.0.0"
edition = "2021"

[dependencies]
cuda_types = { path = "../cuda_types" }
format = { path = "../format" }
uuid = "1.16"
paste = "1.0"
bit-vec = "0.8.0"
cglue = "0.3.5"
