[package]
name = "zluda_precompile"
version = "0.0.0"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
edition = "2021"

[[bin]]
name = "zluda_precompile"
path = "src/main.rs"

[dependencies]
bpaf = { version = "0.9.19", features = ["derive", "bright-color"] }
rayon = "1.11.0"
walkdir = "2"
indicatif = "0.18.3"

[package.metadata.zluda]
