[package]
name = "zluda_dnn8"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "cudnn64_8"

[dependencies]
cuda_macros = { path = "../cuda_macros" }
cuda_types = { path = "../cuda_types" }
zluda_dnn = { path = "../zluda_dnn" }

[package.metadata.zluda]
linux_symlinks = [
    "libcudnn.so.8",
]

[target.'cfg(windows)'.dependencies]
zluda_windows = { path = "../zluda_windows" }
