[package]
name = "zluda_trace_common"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
libloading = "0.8"
cuda_types = { path = "../cuda_types" }
dark_api = { path = "../dark_api" }
format = { path = "../format" }
cglue = "0.3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.142"
tar = "0.4"
zstd = "0.13"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"
