[package]
name = "zluda_dnn"
version = "0.0.0"
edition = "2021"

[lib]

[dependencies]
cuda_macros = { path = "../cuda_macros" }
cuda_types = { path = "../cuda_types" }
zluda_common = { path = "../zluda_common" }
miopen-sys = { path = "../ext/miopen-sys" }
hip_runtime-sys = { path = "../ext/hip_runtime-sys" }
