[package]
name = "zluda_fft"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "cufft"

[dependencies]
cuda_macros = { path = "../cuda_macros" }
cuda_types = { path = "../cuda_types" }

[package.metadata.zluda]
linux_symlinks = [
    "libcufft.so.11",
    "libcufft.so.12",
]
